replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "maxbet111/kbot" # Наприклад: maxbet111/mk-app
  tag: ""
  os: linux
  arch: amd64

secret:
  env:
    - name: "TELE_TOKEN" # ТЕПЕР ІМ'Я ПЕРЕДАЄТЬСЯ ЯВНО
      value: "12345:ABCDE" # Твій токен (або порожньо, якщо через секрети)

securityContext:
  privileged: true
