replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "maxbet111/kbot" 
  tag: "v0.0.1" 
  os: linux
  arch: amd64

# ArgoCD ламається, бо шукає саме цей блок 'secret' (без 's' в кінці)
secret:
  env:
    teleToken: "" # Сюди можна вставити токен, якщо шаблон бере його звідси

# Твій старий блок (можеш залишити, якщо він десь використовується)
secrets:
  teleToken: ""

securityContext:
  privileged: true
