name: CI/CD Kbot

on:
  push:
    branches: [ develop ]

permissions:
  contents: write
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        run: |
          # Генеруємо унікальний тег на основі хешу коміту
          SHA=$(git rev-parse --short HEAD)
          TAG="v1.0.0-${SHA}-linux-amd64"
          
          # Перетворюємо назву репозиторію в нижній регістр для GHCR
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          # Викликаємо make, передаючи змінні напряму
          make image REGISTRY=ghcr.io/maxbet111 VERSION=${TAG}
          make push REGISTRY=ghcr.io/maxbet111 VERSION=${TAG}

      - name: Update Helm Chart Tag
        run: |
          # Оновлюємо значення tag у values.yaml
          sed -i "s/tag: .*/tag: \"${{ env.NEW_TAG }}\"/" helm/values.yaml
          
          # Налаштовуємо Git для коміту від імені бота
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Комітимо та пушимо зміни назад у гілку develop
          git add helm/values.yaml
          git commit -m "chore: update image tag to ${{ env.NEW_TAG }} [skip ci]"
          git push origin develop